include variables.mk

####################
### Build images ###
####################
images: image-drivemgr \
image-node \
image-controller \
image-extender \
image-extender-patcher \
image-scheduler \
image-node-controller

base-images: base-image-drivemgr base-image-node base-image-controller

base-image-drivemgr:
	docker build --network host --file ./pkg/${DRIVE_MANAGER}/${DRIVE_MANAGER_TYPE}/Dockerfile.build \
	--tag ${DRIVE_MANAGER_TYPE}:base ./pkg/${DRIVE_MANAGER}/${DRIVE_MANAGER_TYPE} \
	${BASE_IMAGE_DRIVEMGR_ARGS_${shell echo $(DRIVE_MANAGER_TYPE) | tr '[a-z]' '[A-Z]'}}

download-grpc-health-probe:
	mkdir -p build
	if [ ! -s build/health_probe ]; then curl -L ${HEALTH_PROBE_BIN_URL} -o build/health_probe; fi
	chmod +x build/health_probe

# NOTE: Output directory for binary file should be in Docker context.
# So we can't use csi-baremetal/build to build the image.
base-image-node:
	cp ./build/${HEALTH_PROBE} ./pkg/${NODE}/
	docker build --network host --file ./pkg/${NODE}/Dockerfile.build --tag ${NODE}:base ./pkg/${NODE}
	docker build --network host --file ./pkg/${NODE}/Dockerfile-kernel-5.4.build --tag ${NODE}:base-kernel-5.4 ./pkg/${NODE}

base-image-controller:
	cp ./build/${HEALTH_PROBE} ./pkg/${CONTROLLER}/
	docker build --network host --file ./pkg/${CONTROLLER}/Dockerfile.build --tag ${CONTROLLER}:base ./pkg/${CONTROLLER}

image-drivemgr: base-image-drivemgr
	docker build --network host --force-rm --tag ${REGISTRY}/${PROJECT}-${DRIVE_MANAGER_TYPE}:${TAG} ./pkg/${DRIVE_MANAGER}/${DRIVE_MANAGER_TYPE}

image-node: base-image-node
	docker build --network host --force-rm --tag ${REGISTRY}/${PROJECT}-${NODE}:${TAG} ./pkg/${NODE}
	docker build --network host --force-rm  --file ./pkg/${NODE}/Dockerfile-kernel-5.4 --tag ${REGISTRY}/${PROJECT}-${NODE}-kernel-5.4:${TAG} ./pkg/${NODE}

image-controller: base-image-controller
	docker build --network host --force-rm --tag ${REGISTRY}/${PROJECT}-${CONTROLLER}:${TAG} ./pkg/${CONTROLLER}

image-extender:
	cp ./build/${HEALTH_PROBE} ./build/${SCHEDULING_PKG}/${EXTENDER}/
	docker build --network host --force-rm --tag ${REGISTRY}/${PROJECT}-${SCHEDULER}-${EXTENDER}:${TAG} ./build/${SCHEDULING_PKG}/${EXTENDER}

image-extender-patcher:
	docker build --network host --force-rm --tag ${REGISTRY}/${PROJECT}-${EXTENDER_PATCHER}:${TAG} ./pkg/${SCHEDULER_EXTENDER_PATCHER_PKG}

image-scheduler:
	docker build --network host --force-rm --tag ${REGISTRY}/${PROJECT}-${SCHEDULER}:${TAG} ./pkg/${SCHEDULING_PKG}/${SCHEDULER}

image-node-controller:
	docker build --network host --force-rm --tag ${REGISTRY}/${PROJECT}-${NODE_CONTROLLER}:${TAG} \
	./pkg/${CR_CONTROLLERS}/${NODE_CONTROLLER}

###################
### Push images ###
###################
push: push-drivemgr \
push-node \
push-controller \
push-extender \
push-extender-patcher \
push-scheduler \
push-node-controller

push-drivemgr:
	docker push ${REGISTRY}/${PROJECT}-${DRIVE_MANAGER_TYPE}:${TAG}

push-node:
	docker push ${REGISTRY}/${PROJECT}-${NODE}:${TAG}
	docker push ${REGISTRY}/${PROJECT}-${NODE}-kernel-5.4:${TAG}

push-controller:
	docker push ${REGISTRY}/${PROJECT}-${CONTROLLER}:${TAG}

push-extender:
	docker push ${REGISTRY}/${PROJECT}-${SCHEDULER}-${EXTENDER}:${TAG}

push-extender-patcher:
	docker push ${REGISTRY}/${PROJECT}-${EXTENDER_PATCHER}:${TAG}

push-scheduler:
	docker push ${REGISTRY}/${PROJECT}-${SCHEDULER}:${TAG}

push-node-controller:
	docker push ${REGISTRY}/${PROJECT}-${NODE_CONTROLLER}:${TAG}

####################
### Clean images ###
####################
clean-images: clean-image-node \
clean-image-controller \
clean-image-drivemgr \
clean-image-extender \
clean-image-extender-patcher \
clean-image-scheduler \
clean-image-node-controller

clean-image-drivemgr:
	docker rmi ${REGISTRY}/${PROJECT}-${DRIVE_MANAGER_TYPE}:${TAG}

clean-image-node:
	docker rmi ${REGISTRY}/${PROJECT}-${NODE}:${TAG}
	docker rmi ${REGISTRY}/${PROJECT}-${NODE}-kernel-5.4:${TAG}

clean-image-controller:
	docker rmi ${REGISTRY}/${PROJECT}-${CONTROLLER}:${TAG}

clean-image-extender:
	docker rmi ${REGISTRY}/${PROJECT}-${SCHEDULER}-${EXTENDER}:${TAG}

clean-image-extender-patcher:
	docker rmi ${REGISTRY}/${PROJECT}-${EXTENDER_PATCHER}:${TAG}

clean-image-scheduler:
	docker rmi ${REGISTRY}/${PROJECT}-${SCHEDULER}:${TAG}

clean-image-node-controller:
	docker rmi ${REGISTRY}/${PROJECT}-${NODE_CONTROLLER}:${TAG}
