name: Publish docker images

on:
  push:
    branches:
      - "feature-*"

env:
  REGISTRY: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: Build and publish images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: |
          mkdir build
          make images

      - name: Push images
        run: make push REGISTRY=${{ env.REGISTRY }} PROJECT=${{ github.actor }}
