name: Publish docker images

on:
  push:
    branches:
      - "feature-*"

jobs:
  build:
    name: Build and publish devkit
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set vars
        id: vars
        run: echo "::set-output name=image_repo::ghcr.io/${{ github.repository }}/csi-baremetal-devkit"

      - name: Build and push devkit
        run: make push REPO=${{ steps.vars.outputs.image_repo }}
        working-directory: devkit