name: Publish docker images

on:
  push:
    branches:
      - "feature-*"

jobs:
  build:
    name: Build and publish devkit
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build devkit
        id: build_devkit
        run: make build
        working-directory: devkit