name: Release Charts

on: 
  workflow_dispatch:
    inputs:
      csi_operator_version:
        description: 'Last released CSI Operator version'
        required: true

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Make version
        id: version
        run: echo "::set-output name=version::$(make version)"

      - name: Create asset
        run: |
          PACKAGE_NAME=csi-baremetal-deployment-${{ inputs.csi_operator_version }}.tgz
          DIR=/tmp/csi-baremetal-deployment-${{ steps.version.outputs.version }}
          cp -r ./charts $DIR
          tar -czvf /tmp/$PACKAGE_NAME $DIR

      - name: Update release 
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          repository: dell/csi-baremetal-operator
          files: /tmp/csi-baremetal-deployment-${{ inputs.csi_operator_version }}.tgz
        if: startsWith(github.ref, 'refs/tags/')

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Update helm repository
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"          
